---
# rendered when testing helm 
# Source: three-tier/templates/backend-secret.yaml
# at install time:
#   helm install three-tier ./helm -n three-tier \
#     --set backend.mongoConnStr='mongodb://user:pass@host:27017/tasks?authSource=admin'
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: three-tier
type: Opaque
stringData:
  MONGO_CONN_STR: "will_be_changed"
---
# Source: three-tier/templates/backend-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: three-tier
data:
  PORT: "8080"
---
# Source: three-tier/templates/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: three-tier
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
---
# Source: three-tier/templates/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: three-tier
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
---
# Source: three-tier/templates/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier
spec:
  replicas: 
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "970460117753.dkr.ecr.us-east-1.amazonaws.com/backend-app:0d04eee7fbd300af99b7c86d8cbe9adbba7a4296"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: MONGO_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_CONN_STR
          readinessProbe:
            httpGet:
              path: /ok
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ok
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
